### ISSUE TITLE
Please update version on CPAN

### ISSUE THREAD

**Issue by jcharaoui** [Grinnz/Mojolicious-Plugin-TemplateToolkit#2]
Hello, I'm trying to deploy this package from a CPAN repository, but it's not working because of test failures which are fixed in this repository. Please push an update out to CPAN. Thanks!

**Comment by Grinnz** [comment]
I'll do a release shortly, but it's curious, I made this change several years ago and I'm not sure if I found the cause of the failure; I only see two failing test reports on cpantesters.

**Comment by jcharaoui** [comment]
I could produce the problem on Debian 9.4 using the following command:
`dh-make-perl --build--cpan Mojolicious::Plugin::TemplateToolkit`

**Comment by Grinnz** [comment]
0.003 has been released.
